import { SignJWT, jwtVerify, errors as joseErrors } from "jose";

/**
 * Phase 4K-B — CSRF/replay protection for the Discord bot-install OAuth
 * redirect (http/routes/discordConnections.ts). Same real, maintained-JWT
 * approach as lib/knoveraToken.ts (`jose`, HS256, algorithm-pinned) rather
 * than hand-rolling a nonce store — deliberately reused, not reinvented.
 *
 * Why this shape and not Whop's client-side PKCE flow (src/oauth/whopOAuth.ts):
 * Discord's bot-install authorization (`scope=bot`) has no code/PKCE
 * exchange at all — Discord redirects straight back to our `redirect_uri`
 * with `guild_id` (and our `state`) as plain query params, so the
 * `redirect_uri` must be a server endpoint that can call the Discord API
 * with the bot token immediately. A signed, short-lived, single-purpose
 * state token generated by THAT SAME server just before redirecting is the
 * correct mechanism for this specific OAuth shape — it is "bounded" per
 * the spec's own "single-use or bounded" requirement (10-minute TTL,
 * chosen because a redirect-based browser flow can legitimately take a
 * couple of minutes with a real user picking a guild on Discord's own UI).
 * `redirect_uri` itself is never client-supplied — see
 * discordConnections.ts, which builds it from config.publicApiBaseUrl.
 */

const DISCORD_STATE_TYPE = "discord_connect_state";
const DISCORD_STATE_ALG = "HS256";
export const DISCORD_STATE_TTL_SECONDS = 10 * 60;

function secretKey(secret: string): Uint8Array {
  return new TextEncoder().encode(secret);
}

export async function issueDiscordConnectState(secret: string, ttlSeconds: number = DISCORD_STATE_TTL_SECONDS): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  return new SignJWT({ type: DISCORD_STATE_TYPE })
    .setProtectedHeader({ alg: DISCORD_STATE_ALG, typ: "JWT" })
    .setIssuedAt(now)
    .setExpirationTime(now + ttlSeconds)
    .setJti(crypto.randomUUID())
    .sign(secretKey(secret));
}

/** Returns true only for a signature-valid, correctly-typed, unexpired state token — a single generic outcome (never distinguishing *why* it failed), same principle as verifyKnoveraToken. */
export async function verifyDiscordConnectState(token: string, secret: string): Promise<boolean> {
  try {
    const { payload } = await jwtVerify(token, secretKey(secret), { algorithms: [DISCORD_STATE_ALG] });
    return payload.type === DISCORD_STATE_TYPE;
  } catch (err) {
    if (err instanceof joseErrors.JOSEError) return false;
    throw err;
  }
}
