import { SignJWT, jwtVerify, errors as joseErrors } from "jose";

/**
 * Phase 4K-B — CSRF/replay protection for the Discord bot-install OAuth
 * redirect (http/routes/discordConnections.ts). Same real, maintained-JWT
 * approach as lib/knoveraToken.ts (`jose`, HS256, algorithm-pinned) rather
 * than hand-rolling a nonce store — deliberately reused, not reinvented.
 *
 * Why this shape and not Whop's client-side PKCE flow (src/oauth/whopOAuth.ts):
 * Discord's bot-install authorization (`scope=bot`) has no code/PKCE
 * exchange at all — Discord redirects straight back to our `redirect_uri`
 * with `guild_id` (and our `state`) as plain query params, so the
 * `redirect_uri` must be a server endpoint that can call the Discord API
 * with the bot token immediately. A signed, short-lived, single-purpose
 * state token generated by THAT SAME server just before redirecting is the
 * correct mechanism for this specific OAuth shape — it is "bounded" per
 * the spec's own "single-use or bounded" requirement (10-minute TTL,
 * chosen because a redirect-based browser flow can legitimately take a
 * couple of minutes with a real user picking a guild on Discord's own UI).
 * `redirect_uri` itself is never client-supplied — see
 * discordConnections.ts, which builds it from config.publicApiBaseUrl.
 *
 * Phase 4K-B review fix — the state now also carries the INITIATING
 * identity (req.knoveraOperator, from createStartDiscordConnectHandler)
 * as an `identity` claim, so the callback (a plain, unauthenticated
 * browser redirect — no Authorization header is possible there) can bind
 * the resulting discord_guild_authorizations grant to whoever actually
 * started the connect flow, never to an arbitrary/client-supplied value
 * (spec: "do not trust arbitrary parameters returned by the browser").
 * The `jti` (already present for unpredictability) is now also the
 * single-use key — see db/discordOAuthStateUsesRepo.ts — checked by the
 * callback before this state is trusted for anything.
 */

const DISCORD_STATE_TYPE = "discord_connect_state";
const DISCORD_STATE_ALG = "HS256";
export const DISCORD_STATE_TTL_SECONDS = 10 * 60;

export interface DiscordConnectStatePayload {
  /** The Knovera identity (req.knoveraOperator) that initiated this connect flow — see http/middleware/knoveraAuth.ts. */
  identity: string;
  /** This token's unique id — pass to db/discordOAuthStateUsesRepo.ts's markDiscordOAuthStateUsed to enforce single-use. */
  jti: string;
}

function secretKey(secret: string): Uint8Array {
  return new TextEncoder().encode(secret);
}

export async function issueDiscordConnectState(secret: string, knoveraIdentity: string, ttlSeconds: number = DISCORD_STATE_TTL_SECONDS): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  return new SignJWT({ type: DISCORD_STATE_TYPE, identity: knoveraIdentity })
    .setProtectedHeader({ alg: DISCORD_STATE_ALG, typ: "JWT" })
    .setIssuedAt(now)
    .setExpirationTime(now + ttlSeconds)
    .setJti(crypto.randomUUID())
    .sign(secretKey(secret));
}

/** Returns the embedded {identity, jti} only for a signature-valid, correctly-typed, unexpired, well-formed state token — null for any other failure (a single generic outcome, never distinguishing *why* it failed, same principle as verifyKnoveraToken). Callers still need db/discordOAuthStateUsesRepo.ts's markDiscordOAuthStateUsed for single-use enforcement — this function alone is stateless and would accept the same valid token every time. */
export async function verifyDiscordConnectState(token: string, secret: string): Promise<DiscordConnectStatePayload | null> {
  try {
    const { payload } = await jwtVerify(token, secretKey(secret), { algorithms: [DISCORD_STATE_ALG] });
    if (payload.type !== DISCORD_STATE_TYPE) return null;
    if (typeof payload.identity !== "string" || payload.identity.length === 0) return null;
    if (typeof payload.jti !== "string" || payload.jti.length === 0) return null;
    return { identity: payload.identity, jti: payload.jti };
  } catch (err) {
    if (err instanceof joseErrors.JOSEError) return null;
    throw err;
  }
}
